### ISSUE TITLE
Error when running do_snapshot

### ISSUE THREAD

**Issue by ryanmboyce** [merqlove/do_snapshot#18]
I've had do_snapshot running fine for months via crontab but now I'm getting the following error when running do_snapshot:
```
Start performing operations
Loading list of DigitalOcean droplets
Checking DigitalOcean Access Token.
Setting DigitalOcean Access Token.
SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: sslv3 alert handshake failure
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:921:in `connect'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:921:in `block in connect'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:921:in `connect'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:851:in `start'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1373:in `request'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1131:in `get'
/Library/Ruby/Gems/2.0.0/gems/faraday-0.12.1/lib/faraday/adapter/net_http.rb:78:in `perform_request'
/Library/Ruby/Gems/2.0.0/gems/faraday-0.12.1/lib/faraday/adapter/net_http.rb:38:in `block in call'
/Library/Ruby/Gems/2.0.0/gems/faraday-0.12.1/lib/faraday/adapter/net_http.rb:85:in `with_net_http_connection'
/Library/Ruby/Gems/2.0.0/gems/faraday-0.12.1/lib/faraday/adapter/net_http.rb:33:in `call'
/Library/Ruby/Gems/2.0.0/gems/faraday-0.12.1/lib/faraday/rack_builder.rb:139:in `build_response'
/Library/Ruby/Gems/2.0.0/gems/faraday-0.12.1/lib/faraday/connection.rb:386:in `run_request'
/Library/Ruby/Gems/2.0.0/gems/faraday-0.12.1/lib/faraday/connection.rb:149:in `get'
/Library/Ruby/Gems/2.0.0/gems/barge-0.12.0/lib/barge/resource/base.rb:22:in `public_send'
/Library/Ruby/Gems/2.0.0/gems/barge-0.12.0/lib/barge/resource/base.rb:22:in `request'
/Library/Ruby/Gems/2.0.0/gems/barge-0.12.0/lib/barge/resource/base.rb:16:in `block (2 levels) in <module:Base>'
/Library/Ruby/Gems/2.0.0/gems/barge-0.12.0/lib/barge/resource/droplet.rb:11:in `all'
/Library/Ruby/Gems/2.0.0/gems/do_snapshot-0.6.3/lib/do_snapshot/adapter/digitalocean_v2.rb:25:in `droplets'
/Library/Ruby/Gems/2.0.0/gems/do_snapshot-0.6.3/lib/do_snapshot/command.rb:148:in `load_droplets'
/Library/Ruby/Gems/2.0.0/gems/do_snapshot-0.6.3/lib/do_snapshot/command.rb:137:in `work_with_droplets'
/Library/Ruby/Gems/2.0.0/gems/do_snapshot-0.6.3/lib/do_snapshot/command.rb:20:in `snap'
/Library/Ruby/Gems/2.0.0/gems/do_snapshot-0.6.3/lib/do_snapshot/cli.rb:160:in `snap'
/Library/Ruby/Gems/2.0.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
/Library/Ruby/Gems/2.0.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
/Library/Ruby/Gems/2.0.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
/Library/Ruby/Gems/2.0.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
/Library/Ruby/Gems/2.0.0/gems/do_snapshot-0.6.3/lib/do_snapshot/runner.rb:38:in `run_cli'
/Library/Ruby/Gems/2.0.0/gems/do_snapshot-0.6.3/lib/do_snapshot/runner.rb:17:in `execute!'
/Library/Ruby/Gems/2.0.0/gems/do_snapshot-0.6.3/bin/do_snapshot:15:in `<top (required)>'
/usr/local/bin/do_snapshot:23:in `load'
/usr/local/bin/do_snapshot:23:in `<main>'
Sending e-mail notification.
```

**Comment by merqlove** [comment]
@ryanmboyce, hi, can you describe your OS X version?
As i see, you have  installed do_snapshot as system wide gem?

**Comment by merqlove** [comment]
http://stackoverflow.com/questions/26514402/receiving-ssl-connect-returned-1-errno-0-state-sslv3-read-server-hello-a-sslv3

**Comment by ryanmboyce** [comment]
I have that gem installed:
```
$ gem list httpclient

*** LOCAL GEMS ***

httpclient (2.8.3)
```

**Comment by ryanmboyce** [comment]
Is there a way to disable SSL warnings with the gem? And I have it installed under my username only - I'm running MacOS X 10.12.4 Sierra

**Comment by merqlove** [comment]
@ryanmboyce, hi, hm i'm checked on my sierra book, it works without any warns.
Seems your system still use sslv3., which is globally deprecated...

**Comment by merqlove** [comment]
try to run `gem install httpclient`, it will update ruby's `httpclient`.

**Comment by ryanmboyce** [comment]
I did that and it installed without any errors

```
$ sudo gem install -n /usr/local/bin httpclient
Successfully installed httpclient-2.8.3
Parsing documentation for httpclient-2.8.3
Installing ri documentation for httpclient-2.8.3
```

**Comment by merqlove** [comment]
ok

**Comment by ryanmboyce** [comment]
Is there anyway to disable/ignore SSL warnings with the gem?

**Comment by merqlove** [comment]
https://github.com/merqlove/do_snapshot/tree/nossl
@ryanmboyce try that branch. I'm added parameter for current client, to skip SSL verification.
But any way, if that works for you, pls understand, it is unsafe connection.

**Comment by merqlove** [comment]
Other way, is reinstall ruby with support for updated SSL.
