### ISSUE TITLE
Ruby 2.7.0: undefined method `new' for BigDecimal:Class

### ISSUE THREAD

**Issue by matheusfillipe** [merqlove/do_snapshot#24]
With ruby 2.7.0 which is the default for ubuntu 20.04, most popular dropplet nowadays:
```
$ do_snapshot                                                                                                                
Start performing operations                                                                                                  
Loading list of DigitalOcean droplets                                                                                        
undefined method `new' for BigDecimal:Class                                                                                  
/var/lib/gems/2.7.0/gems/activesupport-4.2.11.3/lib/active_support/core_ext/object/duplicable.rb:111:in `<class:BigDecimal>':
 undefined method `new' for BigDecimal:Class (NoMethodError)                                                                 
        from /var/lib/gems/2.7.0/gems/activesupport-4.2.11.3/lib/active_support/core_ext/object/duplicable.rb:106:in `<top (r
equired)>'                                                                                                                   
        from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'                                         
        from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'                                         
        from /var/lib/gems/2.7.0/gems/activesupport-4.2.11.3/lib/active_support/core_ext/object.rb:3:in `<top (required)>'   
        from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        from /var/lib/gems/2.7.0/gems/activesupport-4.2.11.3/lib/active_support/core_ext.rb:2:in `block in <top (required)>'
        from /var/lib/gems/2.7.0/gems/activesupport-4.2.11.3/lib/active_support/core_ext.rb:1:in `each'
        from /var/lib/gems/2.7.0/gems/activesupport-4.2.11.3/lib/active_support/core_ext.rb:1:in `<top (required)>'
        from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
        from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
```

I understand this might be coming from activesupport. You could add on the README.md that ruby 2.7 is not supported. I got it to run with rubenv after installing 2.6.4 btw.

**Comment by YukiTrace** [comment]
In 2023,I ran into the same issue on newer Ruby versions. Only version Ruby 2.6.4 can only be installed with an old version of OpenSSL. I tried 1.1.1D. I complied it, then made Ruby install with this version of Open SSL. Ruby 2.6.4 now installed. But it seems Digital ocean wasn't happy when I went to create a snapshot. After saving my api key for Do_snapshot, during the API call with the key and do_snapshot, I got an error "SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)". That made me think there was a problem with the OpenSSL version I tried. I don't think I can change the version of openssl after install. Do_snapshot might not work anymore.  I'm not sure. I didn't try every version of OpenSSL. **I would recommend using a different backup tool in 2023 unless this gets updated.** (or maybe there is another way to get it working) I was on a Ubuntu server.
