### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by FrancoisMartin** [merqlove/do_snapshot#3]
Hello,

Thank you for sharing your code. I have a problem when i install do_snapshot.
Just after `gem install do_snapshot`, i do :

`$ do_snapshot help`

And i get :
```
/var/lib/gems/1.9.1/gems/do_snapshot-0.0.13/lib/do_snapshot/cli.rb:191:in `block in try_keys_first': private method `fail' called for DoSnapshot::Log:Class (NoMethodError)
	from /var/lib/gems/1.9.1/gems/do_snapshot-0.0.13/lib/do_snapshot/cli.rb:190:in `each'
	from /var/lib/gems/1.9.1/gems/do_snapshot-0.0.13/lib/do_snapshot/cli.rb:190:in `try_keys_first'
	from /var/lib/gems/1.9.1/gems/do_snapshot-0.0.13/lib/do_snapshot/cli.rb:30:in `initialize'
	from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor.rb:355:in `new'
	from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor.rb:355:in `dispatch'
	from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /var/lib/gems/1.9.1/gems/do_snapshot-0.0.13/bin/do_snapshot:15:in `<top (required)>'
	from /usr/local/bin/do_snapshot:23:in `load'
	from /usr/local/bin/do_snapshot:23:in `<main>'
```
Any idea ?

**Comment by merqlove** [comment]
@FrancoisMartin Hello!
Thanks for report!
I c, it's my bad.

I will fixit shortly!

**Comment by FrancoisMartin** [comment]
Nice ! It works perfectly now :)
Thank you.
